bitbag_adyen_payment_details:
  path: /payment/adyen/details
  controller: bit_bag.sylius_adyen_plugin.controller.shop.payment_details_action

bitbag_adyen_payments:
  path: /payment/adyen/{code}
  controller: bit_bag.sylius_adyen_plugin.controller.shop.payments_action
  defaults:
    code: null

bitbag_adyen_thank_you:
  path: /payment/adyen/{code}/thanks
  controller: bit_bag.sylius_adyen_plugin.controller.shop.redirect_target_action
