bitbag_adyen_process_notifications:
  path: /payment/adyen/{code}/notifications
  controller: bitbag.sylius_adyen_plugin.controller.shop.process_notifications_action

bitbag_adyen_localized:
  resource: "@BitBagSyliusAdyenPlugin/Resources/config/routing/shop_routing_localized.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

bitbag_test:
  path: /test
  controller: bit_bag.sylius_adyen_plugin.controller.test_controller
