sylius_grid:
  grids:
    bitbag_sylius_adyen_plugin_log:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusAdyenPlugin\Entity\Log
      sorting:
        dateTime: desc
      fields:
        level:
          type: twig
          label: bitbag_sylius_adyen_plugin.ui.logging.level
          sortable: ~
          options:
            template: "@BitBagSyliusAdyenPlugin/Admin/Logger/_level.html.twig"
        errorCode:
          type: string
          label: bitbag_sylius_adyen_plugin.ui.logging.error_code
          sortable: ~
        message:
          type: string
          label: bitbag_sylius_adyen_plugin.ui.logging.message
          sortable: ~
        dateTime:
          type: datetime
          label: bitbag_sylius_adyen_plugin.ui.logging.date_time
          sortable: ~
          options:
            format: 'Y-m-d H:i:s'
      filters:
        date:
          type: date
          label: bitbag_sylius_adyen_plugin.ui.logging.search
          options:
            field: dateTime
            label: test
        level:
          type: adyen_log_level
          label: bitbag_sylius_adyen_plugin.ui.logging.level
  templates:
    filter:
      adyen_log_level: "@BitBagSyliusAdyenPlugin/Admin/Logger/Grid/_theme.html.twig"
