sylius_payment:
  resources:
    payment_method:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\PaymentMethodRepository
    payment:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\PaymentRepository
