sylius_resource:
  resources:
    bitbag_sylius_adyen_plugin.adyen_token:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\AdyenTokenRepository
        model: BitBag\SyliusAdyenPlugin\Entity\AdyenToken

    bitbag_sylius_adyen_plugin.refund_payment:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\RefundPaymentRepository
        model: Sylius\RefundPlugin\Entity\RefundPayment

    bitbag_sylius_adyen_plugin.payment_method:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\PaymentMethodRepository
        model: Sylius\Component\Core\Model\PaymentMethod

    bitbag_sylius_adyen_plugin.payment:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\PaymentRepository
        model: Sylius\Component\Core\Model\Payment