sylius_resource:
  resources:
    bitbag_sylius_adyen_plugin.adyen_token:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\AdyenTokenRepository
        model: BitBag\SyliusAdyenPlugin\Entity\AdyenToken

    bitbag_sylius_adyen_plugin.adyen_reference:
      classes:
        repository: BitBag\SyliusAdyenPlugin\Repository\AdyenReferenceRepository
        model: BitBag\SyliusAdyenPlugin\Entity\AdyenReference

    bitbag_sylius_adyen_plugin.log:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusAdyenPlugin\Entity\Log
