winzou_state_machine:
  sylius_order:
    callbacks:
      before:
        bitbag_cancel_payment:
          on: ["cancel"]
          do: [ "@bitbag.sylius_adyen_plugin.callback.request_cancel_callback", "__invoke" ]
          args: [ "object" ]

  sylius_payment:
    transitions:
      capture:
        from: [ new, processing, authorized ]
        to: completed
      process:
        from: [ authorized ]
        to: processing
    callbacks:
      after:
        sylius_resolve_state:
          on: [ "complete", "process", "refund", "authorize", "capture" ]

  sylius_order_payment:
    transitions:
      pay:
        from: [awaiting_payment, partially_paid, authorized, processing]

  sylius_refund_refund_payment:
    transitions:
      confirm:
        from: [new]
        to: completed

  sylius_order_checkout:
    callbacks:
      after:
        bitbag_preserve_cart_upon_redirect:
          on: ["complete"]
          args: ["object"]
          do: ["bitbag.sylius_adyen_plugin.callback.preserve_order_token_upon_redirection_callback", "__invoke"]
