imports:
  - { resource: "@BitBagSyliusAdyenPlugin/Resources/config/sylius/payment_method.yml" }
  - { resource: "@BitBagSyliusAdyenPlugin/Resources/config/sylius/blocks.yml" }
  - { resource: "@BitBagSyliusAdyenPlugin/Resources/config/sylius/state_machine.yml" }
  - { resource: "@BitBagSyliusAdyenPlugin/Resources/config/sylius/resources.yml" }
