bitbag_adyen_shop:
  resource: "@BitBagSyliusAdyenPlugin/Resources/config/routing/shop_routing.yml"
bitbag_adyen_admin:
  prefix: '/%sylius_admin.path_name%'
  resource: "@BitBagSyliusAdyenPlugin/Resources/config/routing/admin_routing.yml"
